---
title: Cothlory.bak
description: Simple archive of my experiences and thoughts
author:
  name: Chang Huang
  email: cothlory@gmail.com

url: https://Cothlory.github.io
git_repo: https://github.com/Cothlory/Cothlory.github.io
license: "[CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/)"



theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - base_pages/archive.md
  - base_pages/games.md
  - base_pages/about.md

minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: auto
  
  date_format: "%-b %-d, %Y" # https://shopify.github.io/liquid/filters/date/

  social_links:
  #  - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         user_url: "https://github.com/Cothlory" }
    - { platform: gitlab,         user_url: "https://gitlab.com/Cothlory" }
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/chang-huang-90805a214/" }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #  - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

exclude:
  - LICENSE
  - '**/LICENSE*'
  - README.md
  - Gemfile
  - Gemfile.lock
  - .git/
  - .github/
  - '**/*.yml'
